version: '2'
services:
  db:
    image: postgres
  web:
    build:
      context: ./
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      DATABASE_URL: $DATABASE_URL
