version: '2'
services:
  db:
    image: postgres
    ports:
      - 5432:5432

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      RAILS_ENV: development

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
