FROM rails:4.2

ENV RAILS_ENV=production

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app/
RUN bundle install
RUN bundle exec rake assets:precompile

CMD ["rails", "server", "-b", "0.0.0.0"]
